FROM ubuntu:bionic

WORKDIR /opt/

COPY requirements.sys requirements.sys
COPY requirements.txt requirements.txt

RUN apt update && xargs apt install -y < requirements.sys
RUN pip3 install -r requirements.txt

## install gtest
RUN wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz && \
    tar -zxvf release-1.10.0.tar.gz && rm release-1.10.0.tar.gz && \
    cd googletest-release-1.10.0 && mkdir -p build && cd build && cmake .. && make install

## install Eigen
RUN wget http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2 && \
    tar -xvjf 3.3.7.tar.bz2 && rm 3.3.7.tar.bz2 && \
    cd eigen-eigen-323c052e1731 && mkdir build && cd build && cmake .. && make install

## install CppAD
RUN git clone https://github.com/coin-or/CppAD.git && \
    cd CppAD && git checkout 20190200.5 && mkdir -p build && \
    cd build && cmake .. && make && make install

WORKDIR /app/

COPY examples examples
COPY include include
COPY tests tests
COPY CMakeLists.txt CMakeLists.txt

RUN mkdir build && cd build && cmake .. && make

CMD ["./build/tests/kinetools-test"]