FROM ubuntu:bionic

WORKDIR /opt/

COPY requirements.sys requirements.sys

RUN apt update && xargs apt install -y < requirements.sys

## install Eigen
RUN wget http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2 && \
    tar -xvjf 3.3.7.tar.bz2 && rm 3.3.7.tar.bz2 && \
    cd eigen-eigen-323c052e1731 && mkdir build && cd build && cmake .. && make install

## install CppAD
RUN git clone https://github.com/coin-or/CppAD.git && \
    cd CppAD && git checkout 20190200.5 && mkdir -p build && \
    cd build && cmake .. && make && make install

WORKDIR /app/